language: node_js
sudo: false
node_js:
  - "8"
cache:
    directories:
      - node_modules
services:
  - mongodb
branches:
  only:
    - master
script:
  - npm run connect-mongodb-test
  - npm run test
