/** Declaration koa-session-mongoose file generated by cixiu */
import * as mongoose from 'mongoose';

interface IOption {
  collection?: string;
  connection?: any;
  expires?: number;
  name?: string;
}

declare class MongooseStore {
  session: mongoose.Model<any>;
  constructor(option?: IOption);
  destroy(id: any): Promise<any>;
  get(id: any): any;
  set(id: any, data: any, maxAge: any, { changed, rolling }: any): any;
  static create(opts: IOption): MongooseStore;
}

declare namespace MongooseStore {}

export = MongooseStore;
